// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type LoginHistory struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	LoginTime sql.NullTime   `json:"login_time"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	Success   bool           `json:"success"`
}

type PasswordResetToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
}

type Permission struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type User struct {
	ID           int32          `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Nin          sql.NullString `json:"nin"`
	Gender       sql.NullString `json:"gender"`
	DateOfBirth  sql.NullTime   `json:"date_of_birth"`
	RoleID       int32          `json:"role_id"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserActivityLog struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	Action      string         `json:"action"`
	Description string         `json:"description"`
	IpAddress   sql.NullString `json:"ip_address"`
	UserAgent   sql.NullString `json:"user_agent"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
