// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO business (
    name, address_one, addres_two, country, phone, email, website, city, state, 
    zip_code, tax_id, tax_rate, logo_url, rounding, currency, timezone, language,
    low_stock_threshold, allow_overselling, payment_type, font, primary_color, motto
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
) RETURNING id, name, motto, address_one, addres_two, country, phone, email, website, city, state, zip_code, tax_id, tax_rate, logo_url, rounding, currency, timezone, language, low_stock_threshold, allow_overselling, payment_type, font, primary_color, created_at, updated_at
`

type CreateBusinessParams struct {
	Name              string         `json:"name"`
	AddressOne        string         `json:"address_one"`
	AddresTwo         sql.NullString `json:"addres_two"`
	Country           string         `json:"country"`
	Phone             sql.NullString `json:"phone"`
	Email             sql.NullString `json:"email"`
	Website           sql.NullString `json:"website"`
	City              sql.NullString `json:"city"`
	State             sql.NullString `json:"state"`
	ZipCode           sql.NullString `json:"zip_code"`
	TaxID             sql.NullString `json:"tax_id"`
	TaxRate           sql.NullString `json:"tax_rate"`
	LogoUrl           sql.NullString `json:"logo_url"`
	Rounding          sql.NullString `json:"rounding"`
	Currency          sql.NullString `json:"currency"`
	Timezone          sql.NullString `json:"timezone"`
	Language          sql.NullString `json:"language"`
	LowStockThreshold sql.NullInt32  `json:"low_stock_threshold"`
	AllowOverselling  sql.NullBool   `json:"allow_overselling"`
	PaymentType       []PaymentType  `json:"payment_type"`
	Font              sql.NullString `json:"font"`
	PrimaryColor      sql.NullString `json:"primary_color"`
	Motto             sql.NullString `json:"motto"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, createBusiness,
		arg.Name,
		arg.AddressOne,
		arg.AddresTwo,
		arg.Country,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.TaxID,
		arg.TaxRate,
		arg.LogoUrl,
		arg.Rounding,
		arg.Currency,
		arg.Timezone,
		arg.Language,
		arg.LowStockThreshold,
		arg.AllowOverselling,
		pq.Array(arg.PaymentType),
		arg.Font,
		arg.PrimaryColor,
		arg.Motto,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Motto,
		&i.AddressOne,
		&i.AddresTwo,
		&i.Country,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.TaxID,
		&i.TaxRate,
		&i.LogoUrl,
		&i.Rounding,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.LowStockThreshold,
		&i.AllowOverselling,
		pq.Array(&i.PaymentType),
		&i.Font,
		&i.PrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBusiness = `-- name: DeleteBusiness :exec
DELETE FROM business WHERE id = $1
`

func (q *Queries) DeleteBusiness(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBusiness, id)
	return err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, name, motto, address_one, addres_two, country, phone, email, website, city, state, zip_code, tax_id, tax_rate, logo_url, rounding, currency, timezone, language, low_stock_threshold, allow_overselling, payment_type, font, primary_color, created_at, updated_at FROM business WHERE id = $1
`

func (q *Queries) GetBusiness(ctx context.Context, id int32) (Business, error) {
	row := q.db.QueryRowContext(ctx, getBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Motto,
		&i.AddressOne,
		&i.AddresTwo,
		&i.Country,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.TaxID,
		&i.TaxRate,
		&i.LogoUrl,
		&i.Rounding,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.LowStockThreshold,
		&i.AllowOverselling,
		pq.Array(&i.PaymentType),
		&i.Font,
		&i.PrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, name, motto, address_one, addres_two, country, phone, email, website, city, state, zip_code, tax_id, tax_rate, logo_url, rounding, currency, timezone, language, low_stock_threshold, allow_overselling, payment_type, font, primary_color, created_at, updated_at FROM business ORDER BY created_at DESC
`

func (q *Queries) ListBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.QueryContext(ctx, listBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Motto,
			&i.AddressOne,
			&i.AddresTwo,
			&i.Country,
			&i.Phone,
			&i.Email,
			&i.Website,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.TaxID,
			&i.TaxRate,
			&i.LogoUrl,
			&i.Rounding,
			&i.Currency,
			&i.Timezone,
			&i.Language,
			&i.LowStockThreshold,
			&i.AllowOverselling,
			pq.Array(&i.PaymentType),
			&i.Font,
			&i.PrimaryColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE business SET
    name = $2,
    address_one = $3,
    addres_two = $4,
    country = $5,
    phone = $6,
    email = $7,
    website = $8,
    city = $9,
    state = $10,
    zip_code = $11,
    tax_id = $12,
    tax_rate = $13,
    logo_url = $14,
    rounding = $15,
    currency = $16,
    timezone = $17,
    language = $18,
    low_stock_threshold = $19,
    allow_overselling = $20,
    payment_type = $21,
    font = $22,
    primary_color = $23,
    motto = $24,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, motto, address_one, addres_two, country, phone, email, website, city, state, zip_code, tax_id, tax_rate, logo_url, rounding, currency, timezone, language, low_stock_threshold, allow_overselling, payment_type, font, primary_color, created_at, updated_at
`

type UpdateBusinessParams struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	AddressOne        string         `json:"address_one"`
	AddresTwo         sql.NullString `json:"addres_two"`
	Country           string         `json:"country"`
	Phone             sql.NullString `json:"phone"`
	Email             sql.NullString `json:"email"`
	Website           sql.NullString `json:"website"`
	City              sql.NullString `json:"city"`
	State             sql.NullString `json:"state"`
	ZipCode           sql.NullString `json:"zip_code"`
	TaxID             sql.NullString `json:"tax_id"`
	TaxRate           sql.NullString `json:"tax_rate"`
	LogoUrl           sql.NullString `json:"logo_url"`
	Rounding          sql.NullString `json:"rounding"`
	Currency          sql.NullString `json:"currency"`
	Timezone          sql.NullString `json:"timezone"`
	Language          sql.NullString `json:"language"`
	LowStockThreshold sql.NullInt32  `json:"low_stock_threshold"`
	AllowOverselling  sql.NullBool   `json:"allow_overselling"`
	PaymentType       []PaymentType  `json:"payment_type"`
	Font              sql.NullString `json:"font"`
	PrimaryColor      sql.NullString `json:"primary_color"`
	Motto             sql.NullString `json:"motto"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, updateBusiness,
		arg.ID,
		arg.Name,
		arg.AddressOne,
		arg.AddresTwo,
		arg.Country,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.TaxID,
		arg.TaxRate,
		arg.LogoUrl,
		arg.Rounding,
		arg.Currency,
		arg.Timezone,
		arg.Language,
		arg.LowStockThreshold,
		arg.AllowOverselling,
		pq.Array(arg.PaymentType),
		arg.Font,
		arg.PrimaryColor,
		arg.Motto,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Motto,
		&i.AddressOne,
		&i.AddresTwo,
		&i.Country,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.TaxID,
		&i.TaxRate,
		&i.LogoUrl,
		&i.Rounding,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.LowStockThreshold,
		&i.AllowOverselling,
		pq.Array(&i.PaymentType),
		&i.Font,
		&i.PrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
