// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PaymentType string

const (
	PaymentTypeCash       PaymentType = "cash"
	PaymentTypePos        PaymentType = "pos"
	PaymentTypeRoomCharge PaymentType = "room_charge"
	PaymentTypeTransfer   PaymentType = "transfer"
)

func (e *PaymentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentType(s)
	case string:
		*e = PaymentType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentType: %T", src)
	}
	return nil
}

type NullPaymentType struct {
	PaymentType PaymentType `json:"payment_type"`
	Valid       bool        `json:"valid"` // Valid is true if PaymentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentType), nil
}

type ActivityLog struct {
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
	Action     string         `json:"action"`
	Details    string         `json:"details"`
	EntityID   int32          `json:"entity_id"`
	EntityType string         `json:"entity_type"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Admin struct {
	ID                    int32          `json:"id"`
	FirstName             string         `json:"first_name"`
	LastName              string         `json:"last_name"`
	Username              string         `json:"username"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	RoleID                int32          `json:"role_id"`
	IsActive              bool           `json:"is_active"`
	EmailVerified         bool           `json:"email_verified"`
	VerificationCode      sql.NullString `json:"verification_code"`
	VerificationExpiresAt sql.NullTime   `json:"verification_expires_at"`
	ResetCode             sql.NullString `json:"reset_code"`
	ResetCodeExpiresAt    sql.NullTime   `json:"reset_code_expires_at"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type Branch struct {
	ID         int32          `json:"id"`
	BusinessID int32          `json:"business_id"`
	Name       string         `json:"name"`
	AddressOne sql.NullString `json:"address_one"`
	AddresTwo  sql.NullString `json:"addres_two"`
	Country    sql.NullString `json:"country"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	Website    sql.NullString `json:"website"`
	City       sql.NullString `json:"city"`
	State      sql.NullString `json:"state"`
	ZipCode    sql.NullString `json:"zip_code"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type Brand struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Logo        sql.NullString `json:"logo"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Business struct {
	ID                int32          `json:"id"`
	OwnerID           int32          `json:"owner_id"`
	Name              string         `json:"name"`
	Motto             sql.NullString `json:"motto"`
	Email             sql.NullString `json:"email"`
	Website           sql.NullString `json:"website"`
	TaxID             sql.NullString `json:"tax_id"`
	TaxRate           sql.NullString `json:"tax_rate"`
	Country           string         `json:"country"`
	LogoUrl           sql.NullString `json:"logo_url"`
	Rounding          sql.NullString `json:"rounding"`
	Currency          sql.NullString `json:"currency"`
	Timezone          sql.NullString `json:"timezone"`
	Language          sql.NullString `json:"language"`
	LowStockThreshold sql.NullInt32  `json:"low_stock_threshold"`
	AllowOverselling  sql.NullBool   `json:"allow_overselling"`
	PaymentType       []PaymentType  `json:"payment_type"`
	Font              sql.NullString `json:"font"`
	PrimaryColor      sql.NullString `json:"primary_color"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type Category struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	ParentID    sql.NullInt32  `json:"parent_id"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Color struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Inventory struct {
	ID          int32        `json:"id"`
	StoreID     int32        `json:"store_id"`
	VariationID int32        `json:"variation_id"`
	Quantity    int32        `json:"quantity"`
	LastUpdated sql.NullTime `json:"last_updated"`
}

type Item struct {
	ID          int32          `json:"id"`
	BrandID     sql.NullInt32  `json:"brand_id"`
	CategoryID  int32          `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ItemType    string         `json:"item_type"`
	IsActive    sql.NullBool   `json:"is_active"`
	NoVariants  sql.NullBool   `json:"no_variants"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ItemImage struct {
	ID          int32         `json:"id"`
	ItemID      sql.NullInt32 `json:"item_id"`
	VariationID sql.NullInt32 `json:"variation_id"`
	Url         string        `json:"url"`
	IsPrimary   sql.NullBool  `json:"is_primary"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type LoginHistory struct {
	ID              int32          `json:"id"`
	UsernameOrEmail string         `json:"username_or_email"`
	LoginTime       sql.NullTime   `json:"login_time"`
	IpAddress       sql.NullString `json:"ip_address"`
	UserAgent       sql.NullString `json:"user_agent"`
	Success         bool           `json:"success"`
	ErrorReason     sql.NullString `json:"error_reason"`
}

type PasswordResetToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
}

type Permission struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

type RefreshToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Revoked   sql.NullBool `json:"revoked"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type Store struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	BranchID     int32          `json:"branch_id"`
	Address      string         `json:"address"`
	Phone        string         `json:"phone"`
	Email        string         `json:"email"`
	IsActive     sql.NullBool   `json:"is_active"`
	StoreType    string         `json:"store_type"`
	StoreCode    string         `json:"store_code"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	AssignedUser sql.NullInt32  `json:"assigned_user"`
	ManagerID    sql.NullInt32  `json:"manager_id"`
}

type StorePrice struct {
	ID          int32  `json:"id"`
	StoreID     int32  `json:"store_id"`
	VariationID int32  `json:"variation_id"`
	Price       string `json:"price"`
}

type Unit struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	ShortCode sql.NullString `json:"short_code"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Gender       sql.NullString `json:"gender"`
	RoleID       sql.NullInt32  `json:"role_id"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Variation struct {
	ID           int32          `json:"id"`
	ItemID       int32          `json:"item_id"`
	Sku          string         `json:"sku"`
	Name         string         `json:"name"`
	UnitID       int32          `json:"unit_id"`
	Size         sql.NullString `json:"size"`
	ColorID      sql.NullInt32  `json:"color_id"`
	Barcode      sql.NullString `json:"barcode"`
	BasePrice    string         `json:"base_price"`
	ReorderLevel sql.NullInt32  `json:"reorder_level"`
	IsDefault    sql.NullBool   `json:"is_default"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
