// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Admin struct {
	ID                    int32          `json:"id"`
	FirstName             string         `json:"first_name"`
	LastName              string         `json:"last_name"`
	Username              string         `json:"username"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	RoleID                int32          `json:"role_id"`
	IsActive              bool           `json:"is_active"`
	EmailVerified         bool           `json:"email_verified"`
	VerificationCode      sql.NullString `json:"verification_code"`
	VerificationExpiresAt sql.NullTime   `json:"verification_expires_at"`
	ResetCode             sql.NullString `json:"reset_code"`
	ResetCodeExpiresAt    sql.NullTime   `json:"reset_code_expires_at"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type LoginHistory struct {
	ID              int32          `json:"id"`
	UsernameOrEmail string         `json:"username_or_email"`
	LoginTime       sql.NullTime   `json:"login_time"`
	IpAddress       sql.NullString `json:"ip_address"`
	UserAgent       sql.NullString `json:"user_agent"`
	Success         bool           `json:"success"`
	ErrorReason     sql.NullString `json:"error_reason"`
}

type PasswordResetToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
}

type Permission struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

type RefreshToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Revoked   sql.NullBool `json:"revoked"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Gender       sql.NullString `json:"gender"`
	RoleID       sql.NullInt32  `json:"role_id"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserActivityLog struct {
	ID         int32           `json:"id"`
	UserID     int32           `json:"user_id"`
	Action     string          `json:"action"`
	Details    json.RawMessage `json:"details"`
	EntityID   int32           `json:"entity_id"`
	EntityType string          `json:"entity_type"`
	IpAddress  sql.NullString  `json:"ip_address"`
	UserAgent  sql.NullString  `json:"user_agent"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}
