// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type PaymentType string

const (
	PaymentTypeCash       PaymentType = "cash"
	PaymentTypePos        PaymentType = "pos"
	PaymentTypeRoomCharge PaymentType = "room_charge"
	PaymentTypeTransfer   PaymentType = "transfer"
)

func (e *PaymentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentType(s)
	case string:
		*e = PaymentType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentType: %T", src)
	}
	return nil
}

type NullPaymentType struct {
	PaymentType PaymentType `json:"payment_type"`
	Valid       bool        `json:"valid"` // Valid is true if PaymentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentType), nil
}

type Admin struct {
	ID                    int32          `json:"id"`
	FirstName             string         `json:"first_name"`
	LastName              string         `json:"last_name"`
	Username              string         `json:"username"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	RoleID                int32          `json:"role_id"`
	IsActive              bool           `json:"is_active"`
	EmailVerified         bool           `json:"email_verified"`
	VerificationCode      sql.NullString `json:"verification_code"`
	VerificationExpiresAt sql.NullTime   `json:"verification_expires_at"`
	ResetCode             sql.NullString `json:"reset_code"`
	ResetCodeExpiresAt    sql.NullTime   `json:"reset_code_expires_at"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type Business struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	Motto             sql.NullString `json:"motto"`
	AddressOne        string         `json:"address_one"`
	AddresTwo         sql.NullString `json:"addres_two"`
	Country           string         `json:"country"`
	Phone             sql.NullString `json:"phone"`
	Email             sql.NullString `json:"email"`
	Website           sql.NullString `json:"website"`
	City              sql.NullString `json:"city"`
	State             sql.NullString `json:"state"`
	ZipCode           sql.NullString `json:"zip_code"`
	TaxID             sql.NullString `json:"tax_id"`
	TaxRate           sql.NullString `json:"tax_rate"`
	LogoUrl           sql.NullString `json:"logo_url"`
	Rounding          sql.NullString `json:"rounding"`
	Currency          sql.NullString `json:"currency"`
	Timezone          sql.NullString `json:"timezone"`
	Language          sql.NullString `json:"language"`
	LowStockThreshold sql.NullInt32  `json:"low_stock_threshold"`
	AllowOverselling  sql.NullBool   `json:"allow_overselling"`
	PaymentType       []PaymentType  `json:"payment_type"`
	Font              sql.NullString `json:"font"`
	PrimaryColor      sql.NullString `json:"primary_color"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type LoginHistory struct {
	ID              int32          `json:"id"`
	UsernameOrEmail string         `json:"username_or_email"`
	LoginTime       sql.NullTime   `json:"login_time"`
	IpAddress       sql.NullString `json:"ip_address"`
	UserAgent       sql.NullString `json:"user_agent"`
	Success         bool           `json:"success"`
	ErrorReason     sql.NullString `json:"error_reason"`
}

type PasswordResetToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
}

type Permission struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

type RefreshToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Revoked   sql.NullBool `json:"revoked"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Gender       sql.NullString `json:"gender"`
	RoleID       sql.NullInt32  `json:"role_id"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserActivityLog struct {
	ID         int32           `json:"id"`
	UserID     int32           `json:"user_id"`
	Action     string          `json:"action"`
	Details    json.RawMessage `json:"details"`
	EntityID   int32           `json:"entity_id"`
	EntityType string          `json:"entity_type"`
	IpAddress  sql.NullString  `json:"ip_address"`
	UserAgent  sql.NullString  `json:"user_agent"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}
